version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
      java: corretto8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - curl -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-4.7.0.2747-linux/bin
      - echo "Create ZIP deployment package"
      - zip -r "cab-booking-app" . 
      # - echo "Copying zip to S3"
      # - aws s3 cp cab-booking-app.zip s3://23410698-cab-booking/  
  

  build:
    commands:
      - echo "Running Pylint static analysis..."
      - echo "doing ls"
      - ls
      - find . -name "*.py" | xargs pylint --fail-under=7
      - echo "Running SonarQube security analysis..."
      - sonar-scanner -Dsonar.projectKey=cab-booking -Dsonar.sources=. -Dsonar.host.url=http://3.250.106.200:9000 -Dsonar.login=sqa_83f6d10852b8673122895d026cfaacd042d6b26f

  post_build:
    commands:
      - echo "Preparing for deployment..."
      # - echo "Create new ElasticBeanstalk Applicaiton Version"
      # - aws elasticbeanstalk create-application-version --application-name 23410698_vyom_cab_booking --version-label v1 --source-bundle S3Bucket="23410698-cab-booking",S3Key="cab-booking-app.zip"
      # - aws elasticbeanstalk update-environment --application-name 23410698_vyom_cab_booking --environment-name 23410698vyomcabbooking-env --version-label v1
      # - echo "Deployment done successfully!!"
        

artifacts:
  files:
    - cab-booking-app.zip
