version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
      java: corretto8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - curl -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-4.7.0.2747-linux/bin
      - echo "Create ZIP deployment package"
      - zip -r cab-booking-app.zip .  

  build:
    commands:
      - echo "Running Pylint static analysis..."
      - echo "doing ls"
      - ls
      - find . -name "*.py" | xargs pylint --fail-under=7
      - echo "Running SonarQube security analysis..."
      - sonar-scanner -Dsonar.projectKey=cab-booking -Dsonar.sources=. -Dsonar.host.url=http:/54.195.181.242:9000 -Dsonar.login=sqa_3f4d3f4661ae98954f2aa5a14d26940aff04948d

artifacts:
  files:
    # - cab-booking-app.zip
    - '**/*'
